create table QUESTMASTER(
   QSLNO INT NOT NULL AUTO_INCREMENT,
   SETNO CHAR(2),
   QUSETSLNO INT NOT NULL,
   QUESTION VARCHAR(500) NOT NULL,
   ANS1 VARCHAR(40),
   ANS2 VARCHAR(40),
   ANS3 VARCHAR(40),
   ANS4 VARCHAR(40),
   ANS5 VARCHAR(40),
   PARAGRAPH VARCHAR(500),
   RTANS INT,
   ISSINGLE INT NOT NULL,
   AMARK INT NOT NULL,
   USERID VARCHAR(40) NOT NULL,
   DATE DATE,
   PRIMARY KEY ( QSLNO )
)