create table REULTMASTER(
   RSLNO INT NOT NULL AUTO_INCREMENT,
   SETNO CHAR(2),
   QUSETSLNO INT NOT NULL,
   PARAANS VARCHAR(40),
   SELANS VARCHAR(40),
   RMARK VARCHAR(40),
   APPLICANTID CHAR(10),
   DATE DATE,
   PRIMARY KEY ( RSLNO )
)