create table USERMASTER(
   USLNO INT NOT NULL AUTO_INCREMENT,
   MOBNO INT(10),
   FSTNAME VARCHAR(40) NOT NULL,
   MIDNAME VARCHAR(40),
   LASTNM VARCHAR(40) NOT NULL,
   EMAIL VARCHAR(40),
   PAN CHAR(10),
   ADDRESS VARCHAR(500),
   APPLICANTID CHAR(10) NOT NULL,
   DATE DATE,
   PRIMARY KEY ( USLNO, APPLICANTID )
)




USLNO	MOBNO	FSTNAME	MIDNAME	LASTNM	EMAIL	PAN	ADDRESS	APPLICANTID
